### ISSUE TITLE
Make package and import name be the same.

### ISSUE THREAD

**Issue by zkbt** [zkbt/exoatlas#41]
Avoid confusion! 

'`exoplanetatlas`? `exoplanet_atlas`?

**Comment by zkbt** [comment]
Ha! I discovered the hilarious and deeply weird thing that PyPI replaces all `_` with `-`, and of course Python can't `import` a package with a `-` in it. So, I'm going with `exoplanet-atlas` for GitHub and PyPI, and `exoplanet_atlas` for the import name. I suspect this will still cause confusion, but I like having the `-/_` in there just to make the name more legible.

**Comment by gmduvvuri** [comment]
Was `exoatlas` ever on the table or is that not explicit enough?

**Comment by zkbt** [comment]
Oh, fair enough, that's simpler and nicer and solves this ridiculous PyPI problem. I'll just switch everything to `exoatlas`. It even makes more sense, because I want to have stars in here too for some various projects, so not having `planet` in the name is probably actually a feature.
